DROP TABLE IF EXISTS places;

CREATE TABLE places
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  city_name VARCHAR(100) NOT NULL,
  state_name VARCHAR(100),
  country_name VARCHAR(100),
  latitude DOUBLE NOT NULL,
  longitude DOUBLE NOT NULL
) ENGINE=InnoDB;
